// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Archives (Phase 4B: delegated to domains/archives) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Archives (Phase 4B: delegated to domains/archives) ==========
  // BUILD 19E_CBR_LAZY_IPC (Build 19E)
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.CBR_OPEN, (e, ...args) => domains.archivesDomain.cbrOpen(ctx, e, ...args));
  ipcMain.handle(CHANNEL.CBR_OPEN, (e, ...args) => domains.archivesDomain.cbrOpen(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.CBR_READ_ENTRY, (e, ...args) => domains.archivesDomain.cbrReadEntry(ctx, e, ...args));
  ipcMain.handle(CHANNEL.CBR_READ_ENTRY, (e, ...args) => domains.archivesDomain.cbrReadEntry(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.CBR_CLOSE, (e, ...args) => domains.archivesDomain.cbrClose(ctx, e, ...args));
  ipcMain.handle(CHANNEL.CBR_CLOSE, (e, ...args) => domains.archivesDomain.cbrClose(ctx, e, ...args));

  // BUILD 19D_CBZ_LAZY_IPC (Build 19D)
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.CBZ_OPEN, (e, ...args) => domains.archivesDomain.cbzOpen(ctx, e, ...args));
  ipcMain.handle(CHANNEL.CBZ_OPEN, (e, ...args) => domains.archivesDomain.cbzOpen(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.CBZ_READ_ENTRY, (e, ...args) => domains.archivesDomain.cbzReadEntry(ctx, e, ...args));
  ipcMain.handle(CHANNEL.CBZ_READ_ENTRY, (e, ...args) => domains.archivesDomain.cbzReadEntry(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.CBZ_CLOSE, (e, ...args) => domains.archivesDomain.cbzClose(ctx, e, ...args));
  ipcMain.handle(CHANNEL.CBZ_CLOSE, (e, ...args) => domains.archivesDomain.cbzClose(ctx, e, ...args));


};
