// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Export (Phase 4B: delegated to domains/export) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Export (Phase 4B: delegated to domains/export) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.EXPORT_SAVE_ENTRY, (e, ...args) => domains.exportDomain.saveEntry(ctx, e, ...args));
  ipcMain.handle(CHANNEL.EXPORT_SAVE_ENTRY, (e, ...args) => domains.exportDomain.saveEntry(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.EXPORT_COPY_ENTRY, (e, ...args) => domains.exportDomain.copyEntry(ctx, e, ...args));
  ipcMain.handle(CHANNEL.EXPORT_COPY_ENTRY, (e, ...args) => domains.exportDomain.copyEntry(ctx, e, ...args));


};
