// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Health Check (BUILD 88 FIX 3.2) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Health Check (BUILD 88 FIX 3.2) ==========
  // Simple ping to test main process responsiveness
  // TRACE:IPC_IN ipcMain.handle(CHANNEL.HEALTH_PING, async () => {
  // BUILD88: main/ipc/index.js may pre-register HEALTH_PING as a safety net.
  // Remove any existing handler first so this module never throws duplicate-handler errors.
  try { ipcMain.removeHandler(CHANNEL.HEALTH_PING); } catch {}
  ipcMain.handle(CHANNEL.HEALTH_PING, async () => {
    const startTime = Date.now();
    // Minimal work - just return timestamp
    return { ok: true, timestamp: startTime };
  });


};
