// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Library (Phase 4C: delegated to domains/library) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Library (Phase 4C: delegated to domains/library) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_GET_STATE, (e, ...args) => domains.libraryDomain.getState(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_GET_STATE, (e, ...args) => domains.libraryDomain.getState(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_SCAN, (e, ...args) => domains.libraryDomain.scan(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_SCAN, (e, ...args) => domains.libraryDomain.scan(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_CANCEL_SCAN, (e, ...args) => domains.libraryDomain.cancelScan(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_CANCEL_SCAN, (e, ...args) => domains.libraryDomain.cancelScan(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_SET_SCAN_IGNORE, (e, ...args) => domains.libraryDomain.setScanIgnore(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_SET_SCAN_IGNORE, (e, ...args) => domains.libraryDomain.setScanIgnore(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_ADD_ROOT_FOLDER, (e, ...args) => domains.libraryDomain.addRootFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_ADD_ROOT_FOLDER, (e, ...args) => domains.libraryDomain.addRootFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_REMOVE_ROOT_FOLDER, (e, ...args) => domains.libraryDomain.removeRootFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_REMOVE_ROOT_FOLDER, (e, ...args) => domains.libraryDomain.removeRootFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_ADD_SERIES_FOLDER, (e, ...args) => domains.libraryDomain.addSeriesFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_ADD_SERIES_FOLDER, (e, ...args) => domains.libraryDomain.addSeriesFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_REMOVE_SERIES_FOLDER, (e, ...args) => domains.libraryDomain.removeSeriesFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_REMOVE_SERIES_FOLDER, (e, ...args) => domains.libraryDomain.removeSeriesFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_UNIGNORE_SERIES, (e, ...args) => domains.libraryDomain.unignoreSeries(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_UNIGNORE_SERIES, (e, ...args) => domains.libraryDomain.unignoreSeries(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.LIBRARY_CLEAR_IGNORED_SERIES, (e, ...args) => domains.libraryDomain.clearIgnoredSeries(ctx, e, ...args));
  ipcMain.handle(CHANNEL.LIBRARY_CLEAR_IGNORED_SERIES, (e, ...args) => domains.libraryDomain.clearIgnoredSeries(ctx, e, ...args));




};
