// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Page Thumbnails (Phase 4C: delegated to domains/thumbs) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Page Thumbnails (Phase 4C: delegated to domains/thumbs) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PAGE_THUMBS_HAS, (e, ...args) => domains.thumbsDomain.pageThumbsHas(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PAGE_THUMBS_HAS, (e, ...args) => domains.thumbsDomain.pageThumbsHas(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PAGE_THUMBS_GET, (e, ...args) => domains.thumbsDomain.pageThumbsGet(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PAGE_THUMBS_GET, (e, ...args) => domains.thumbsDomain.pageThumbsGet(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PAGE_THUMBS_SAVE, (e, ...args) => domains.thumbsDomain.pageThumbsSave(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PAGE_THUMBS_SAVE, (e, ...args) => domains.thumbsDomain.pageThumbsSave(ctx, e, ...args));

  // ---------- IPC: Files ----------
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.FILE_READ, async (_evt, filePath) => domains.filesDomain.read(ctx, _evt, filePath));
  ipcMain.handle(CHANNEL.FILE_READ, async (_evt, filePath) => domains.filesDomain.read(ctx, _evt, filePath));


};
