// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Progress (Phase 4A: delegated to domains/progress) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Progress (Phase 4A: delegated to domains/domains.progress) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PROGRESS_GET_ALL, (e, ...args) => domains.progress.getAll(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PROGRESS_GET_ALL, (e, ...args) => domains.progress.getAll(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PROGRESS_GET, (e, ...args) => domains.progress.get(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PROGRESS_GET, (e, ...args) => domains.progress.get(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PROGRESS_SAVE, (e, ...args) => domains.progress.save(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PROGRESS_SAVE, (e, ...args) => domains.progress.save(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PROGRESS_CLEAR, (e, ...args) => domains.progress.clear(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PROGRESS_CLEAR, (e, ...args) => domains.progress.clear(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.PROGRESS_CLEAR_ALL, (e, ...args) => domains.progress.clearAll(ctx, e, ...args));
  ipcMain.handle(CHANNEL.PROGRESS_CLEAR_ALL, (e, ...args) => domains.progress.clearAll(ctx, e, ...args));


};
