// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Series Settings (Phase 4A: delegated to domains/seriesSettings) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Series Settings (Phase 4A: delegated to domains/domains.seriesSettings) ==========
  // Stored in userData/series_settings.json as: { [seriesId]: { settings: {...}, updatedAt } }
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.SERIES_SETTINGS_GET_ALL, (e, ...args) => domains.seriesSettings.getAll(ctx, e, ...args));
  ipcMain.handle(CHANNEL.SERIES_SETTINGS_GET_ALL, (e, ...args) => domains.seriesSettings.getAll(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.SERIES_SETTINGS_GET, (e, ...args) => domains.seriesSettings.get(ctx, e, ...args));
  ipcMain.handle(CHANNEL.SERIES_SETTINGS_GET, (e, ...args) => domains.seriesSettings.get(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.SERIES_SETTINGS_SAVE, (e, ...args) => domains.seriesSettings.save(ctx, e, ...args));
  ipcMain.handle(CHANNEL.SERIES_SETTINGS_SAVE, (e, ...args) => domains.seriesSettings.save(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.SERIES_SETTINGS_CLEAR, (e, ...args) => domains.seriesSettings.clear(ctx, e, ...args));
  ipcMain.handle(CHANNEL.SERIES_SETTINGS_CLEAR, (e, ...args) => domains.seriesSettings.clear(ctx, e, ...args));


};
