// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Video Posters (Phase 4C: delegated to domains/thumbs) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Video Posters (Phase 4C: delegated to domains/thumbs) ==========
  // PHASE 4C NOTE: Video poster path management moved to thumbs domain.
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_POSTER_GET, (e, ...args) => domains.thumbsDomain.videoPosterGet(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_POSTER_GET, (e, ...args) => domains.thumbsDomain.videoPosterGet(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_POSTER_HAS, (e, ...args) => domains.thumbsDomain.videoPosterHas(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_POSTER_HAS, (e, ...args) => domains.thumbsDomain.videoPosterHas(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_POSTER_DELETE, (e, ...args) => domains.thumbsDomain.videoPosterDelete(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_POSTER_DELETE, (e, ...args) => domains.thumbsDomain.videoPosterDelete(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_POSTER_SAVE, (e, ...args) => domains.thumbsDomain.videoPosterSave(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_POSTER_SAVE, (e, ...args) => domains.thumbsDomain.videoPosterSave(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_POSTER_PASTE, (e, ...args) => domains.thumbsDomain.videoPosterPaste(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_POSTER_PASTE, (e, ...args) => domains.thumbsDomain.videoPosterPaste(ctx, e, ...args));


};
