// AUTO-GENERATED by Nirvana 10 split
// ========== IPC: Video UI State (delegated to domains/videoUi) ==========
//
// NOTE (Qt-only cleanup):
// Embedded mpv/libmpv IPC handlers were removed because embedded playback is deprecated in this repo line.
// The detached Python/Qt player is launched via player_core.launchQt.

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  ipcMain.handle(CHANNEL.VIDEO_UI_GET, (e, ...args) => domains.videoUi.get(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_UI_SAVE, (e, ...args) => domains.videoUi.save(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_UI_CLEAR, (e, ...args) => domains.videoUi.clear(ctx, e, ...args));
};
