// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Video (Phase 4C: delegated to domains/video) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Video (Phase 4C: delegated to domains/video) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_GET_STATE, (e, ...args) => domains.videoDomain.getState(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_GET_STATE, (e, ...args) => domains.videoDomain.getState(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_GET_EPISODES_FOR_SHOW, (e, ...args) => domains.videoDomain.getEpisodesForShow(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_GET_EPISODES_FOR_SHOW, (e, ...args) => domains.videoDomain.getEpisodesForShow(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_GET_EPISODES_FOR_ROOT, (e, ...args) => domains.videoDomain.getEpisodesForRoot(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_GET_EPISODES_FOR_ROOT, (e, ...args) => domains.videoDomain.getEpisodesForRoot(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_GET_EPISODES_BY_IDS, (e, ...args) => domains.videoDomain.getEpisodesByIds(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_GET_EPISODES_BY_IDS, (e, ...args) => domains.videoDomain.getEpisodesByIds(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_SCAN, (e, ...args) => domains.videoDomain.scan(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_SCAN, (e, ...args) => domains.videoDomain.scan(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_SCAN_SHOW, (e, ...args) => domains.videoDomain.scanShow(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_SCAN_SHOW, (e, ...args) => domains.videoDomain.scanShow(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_GENERATE_SHOW_THUMBNAIL, (e, ...args) => domains.videoDomain.generateShowThumbnail(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_GENERATE_SHOW_THUMBNAIL, (e, ...args) => domains.videoDomain.generateShowThumbnail(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_CANCEL_SCAN, (e, ...args) => domains.videoDomain.cancelScan(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_CANCEL_SCAN, (e, ...args) => domains.videoDomain.cancelScan(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_ADD_FOLDER, (e, ...args) => domains.videoDomain.addFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_ADD_FOLDER, (e, ...args) => domains.videoDomain.addFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_ADD_SHOW_FOLDER, (e, ...args) => domains.videoDomain.addShowFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_ADD_SHOW_FOLDER, (e, ...args) => domains.videoDomain.addShowFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_REMOVE_FOLDER, (e, ...args) => domains.videoDomain.removeFolder(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_REMOVE_FOLDER, (e, ...args) => domains.videoDomain.removeFolder(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_HIDE_SHOW, (e, ...args) => domains.videoDomain.hideShow(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_HIDE_SHOW, (e, ...args) => domains.videoDomain.hideShow(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_OPEN_FILE_DIALOG, (e, ...args) => domains.videoDomain.openFileDialog(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_OPEN_FILE_DIALOG, (e, ...args) => domains.videoDomain.openFileDialog(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_OPEN_SUBTITLE_FILE_DIALOG, (e, ...args) => domains.videoDomain.openSubtitleFileDialog(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_OPEN_SUBTITLE_FILE_DIALOG, (e, ...args) => domains.videoDomain.openSubtitleFileDialog(ctx, e, ...args));

    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_ADD_FILES, (e, ...args) => domains.videoDomain.addFiles(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_ADD_FILES, (e, ...args) => domains.videoDomain.addFiles(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_REMOVE_FILE, (e, ...args) => domains.videoDomain.removeFile(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_REMOVE_FILE, (e, ...args) => domains.videoDomain.removeFile(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_RESTORE_ALL_HIDDEN_SHOWS, (e, ...args) => domains.videoDomain.restoreAllHiddenShows(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_RESTORE_ALL_HIDDEN_SHOWS, (e, ...args) => domains.videoDomain.restoreAllHiddenShows(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_RESTORE_HIDDEN_SHOWS_FOR_ROOT, (e, ...args) => domains.videoDomain.restoreHiddenShowsForRoot(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_RESTORE_HIDDEN_SHOWS_FOR_ROOT, (e, ...args) => domains.videoDomain.restoreHiddenShowsForRoot(ctx, e, ...args));



  // ---------- IPC: Open File (no library add) ----------
  // BUILD 19E_OPEN_FILE (Build 19E)
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.COMIC_OPEN_FILE_DIALOG, async (evt) => domains.comicDomain.openFileDialog(ctx, evt));
  ipcMain.handle(CHANNEL.COMIC_OPEN_FILE_DIALOG, async (evt) => domains.comicDomain.openFileDialog(ctx, evt));

  // BUILD26_BOOK_FROM_PATH (Build 26)
  // INTENT: Given an on-disk path, return the same "book" object shape used by Open File dialog.
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.COMIC_BOOK_FROM_PATH, async (_evt, filePath) => domains.comicDomain.bookFromPath(ctx, _evt, filePath));
  ipcMain.handle(CHANNEL.COMIC_BOOK_FROM_PATH, async (_evt, filePath) => domains.comicDomain.bookFromPath(ctx, _evt, filePath));




  // ---------- IPC: Thumbnails ----------
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.THUMBS_GET, async (_evt, bookId) => domains.thumbsDomain.thumbsGet(ctx, _evt, bookId));
  ipcMain.handle(CHANNEL.THUMBS_GET, async (_evt, bookId) => domains.thumbsDomain.thumbsGet(ctx, _evt, bookId));


    // TRACE:IPC_IN ipcMain.handle(CHANNEL.THUMBS_DELETE, async (_evt, bookId) => domains.thumbsDomain.thumbsDelete(ctx, _evt, bookId));
  ipcMain.handle(CHANNEL.THUMBS_DELETE, async (_evt, bookId) => domains.thumbsDomain.thumbsDelete(ctx, _evt, bookId));

    // TRACE:IPC_IN ipcMain.handle(CHANNEL.THUMBS_HAS, async (_evt, bookId) => domains.thumbsDomain.thumbsHas(ctx, _evt, bookId));
  ipcMain.handle(CHANNEL.THUMBS_HAS, async (_evt, bookId) => domains.thumbsDomain.thumbsHas(ctx, _evt, bookId));

    // TRACE:IPC_IN ipcMain.handle(CHANNEL.THUMBS_SAVE, async (_evt, bookId, dataUrl) => domains.thumbsDomain.thumbsSave(ctx, _evt, bookId, dataUrl));
  ipcMain.handle(CHANNEL.THUMBS_SAVE, async (_evt, bookId, dataUrl) => domains.thumbsDomain.thumbsSave(ctx, _evt, bookId, dataUrl));


  // ---------- IPC: Video Posters ----------

};
