// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Video Settings (Phase 4A: delegated to domains/videoSettings) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Video Settings (Phase 4A: delegated to domains/domains.videoSettings) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_SETTINGS_GET, (e, ...args) => domains.videoSettings.get(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_SETTINGS_GET, (e, ...args) => domains.videoSettings.get(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_SETTINGS_SAVE, (e, ...args) => domains.videoSettings.save(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_SETTINGS_SAVE, (e, ...args) => domains.videoSettings.save(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.VIDEO_SETTINGS_CLEAR, (e, ...args) => domains.videoSettings.clear(ctx, e, ...args));
  ipcMain.handle(CHANNEL.VIDEO_SETTINGS_CLEAR, (e, ...args) => domains.videoSettings.clear(ctx, e, ...args));


};
