// AUTO-GENERATED by Nirvana 10 split
// // ========== IPC: Window (Phase 4B: delegated to domains/window) ==========

module.exports = function register({ ipcMain, CHANNEL, ctx, domains }) {
  // ========== IPC: Window (Phase 4B: delegated to domains/window) ==========
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_SET_FULLSCREEN, (e, ...args) => domains.windowDomain.setFullscreen(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_SET_FULLSCREEN, (e, ...args) => domains.windowDomain.setFullscreen(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_TOGGLE_FULLSCREEN, (e, ...args) => domains.windowDomain.toggleFullscreen(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_TOGGLE_FULLSCREEN, (e, ...args) => domains.windowDomain.toggleFullscreen(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_IS_FULLSCREEN, (e, ...args) => domains.windowDomain.isFullscreen(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_IS_FULLSCREEN, (e, ...args) => domains.windowDomain.isFullscreen(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_OPEN_BOOK_IN_NEW_WINDOW, (e, ...args) => domains.windowDomain.openBookInNewWindow(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_OPEN_BOOK_IN_NEW_WINDOW, (e, ...args) => domains.windowDomain.openBookInNewWindow(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_OPEN_VIDEO_SHELL, (e, ...args) => domains.windowDomain.openVideoShell(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_OPEN_VIDEO_SHELL, (e, ...args) => domains.windowDomain.openVideoShell(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_MINIMIZE, (e, ...args) => domains.windowDomain.minimize(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_MINIMIZE, (e, ...args) => domains.windowDomain.minimize(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_CLOSE, (e, ...args) => domains.windowDomain.close(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_CLOSE, (e, ...args) => domains.windowDomain.close(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_IS_ALWAYS_ON_TOP, (e, ...args) => domains.windowDomain.isAlwaysOnTop(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_IS_ALWAYS_ON_TOP, (e, ...args) => domains.windowDomain.isAlwaysOnTop(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_TOGGLE_ALWAYS_ON_TOP, (e, ...args) => domains.windowDomain.toggleAlwaysOnTop(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_TOGGLE_ALWAYS_ON_TOP, (e, ...args) => domains.windowDomain.toggleAlwaysOnTop(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_TAKE_SCREENSHOT, (e, ...args) => domains.windowDomain.takeScreenshot(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_TAKE_SCREENSHOT, (e, ...args) => domains.windowDomain.takeScreenshot(ctx, e, ...args));
    // TRACE:IPC_IN ipcMain.handle(CHANNEL.WINDOW_OPEN_SUBTITLE_DIALOG, (e, ...args) => domains.windowDomain.openSubtitleDialog(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_OPEN_SUBTITLE_DIALOG, (e, ...args) => domains.windowDomain.openSubtitleDialog(ctx, e, ...args));

  // BUILD14: Hide/Show window handlers
  ipcMain.handle(CHANNEL.WINDOW_HIDE, (e, ...args) => domains.windowDomain.hideWindow(ctx, e, ...args));
  ipcMain.handle(CHANNEL.WINDOW_SHOW, (e, ...args) => domains.windowDomain.showWindow(ctx, e, ...args));

};
